### ISSUE TITLE
[BUG] Poe 登录提示 Something went wrong...

### ISSUE THREAD

**Issue by Smartyaostudent** [lss233/chatgpt-mirai-qq-bot#705]
**提交 issue 前，请先确认：**
- [x] 我已看过 **FAQ**，此问题不在列表中
- [ ] 我已看过其他 issue，他们不能解决我的问题 
- [ ] 我认为这不是 Mirai 或者 OpenAI 的 BUG

**表现**  
描述 BUG 的表现情况

**运行环境:**  
- 操作系统：？
- Docker： ？
- 项目版本：？

**复现步骤**  
描述你是如何触发这个 BUG 的

**预期行为**  
描述你认为正常情况下应该看见的情况

**截图**  
相关日志、聊天记录的截图，没有可跳过

**其他内容**  
此处填写其他内容，没有可跳过

**Comment by Smartyaostudent** [comment]
[]
![image](https://user-images.githubusercontent.com/85338367/234339336-68e0345f-58fe-44a8-9bcc-d89df6c8652d.png)
(url)
如图，使用一键部署，发现poe，反应慢中断，结果查看原poe界面发现，poe无法登陆，这个是被封了吗？

**Comment by laoqin6** [comment]
好像是poe的问题

**Comment by Smartyaostudent** [comment]
我三个号都寄了😂😂😂Sent from my phone-------- Original message --------From: 老秦 ***@***.***>Date: Wed, Apr 26, 2023, 2:22 PMTo: lss233/chatgpt-mirai-qq-bot ***@***.***>Cc: Yao Keyang ***@***.***>, Author ***@***.***>Subject: Re: [lss233/chatgpt-mirai-qq-bot] [BUG] 请填写标题 (Issue #705)
好像是poe的问题

**Comment by lss233** [comment]
应该是被 Poe 封号了，目前没有解决方法。  是不是你的使用频率比较高？

**Comment by laoqin6** [comment]
> 我三个号都寄了😂😂😂Sent from my phone-------- Original message --------From: 老秦 ***@***.***>Date: Wed, Apr 26, 2023, 2:22 PMTo: lss233/chatgpt-mirai-qq-bot ***@***.***>Cc: Yao Keyang ***@***.***>, Author ***@***.***>Subject: Re: [lss233/chatgpt-mirai-qq-bot] [BUG] 请填写标题 (Issue #705) 好像是poe的问题 —Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>

我有两个号 我昨天和你一样 然后下午我重新登了一下 有一个号进去了 又可以用了 另外一个不行 噗

**Comment by laoqin6** [comment]
> 

没有吧，我现在都还在注册

**Comment by laoqin6** [comment]
> [ading2210/poe-api#54](https://github.com/ading2210/poe-api/issues/54) poe似乎会封IP和设备 我现在都没法注册

没有吧，我现在都还可以注册

**Comment by 2658548663** [comment]
我的poe也被封号了，不能使用poe，跟使用频率啥的无关

**Comment by laoqin6** [comment]
我的都解封了- -








------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "lss233/chatgpt-mirai-qq-bot"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年5月19日(星期五) 下午4:39
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [lss233/chatgpt-mirai-qq-bot] [BUG] Poe 登录提示 Something went wrong... (Issue #705)





 
我的poe也被封号了，不能使用poe，跟使用频率啥的无关

**Comment by 2658548663** [comment]
> 我的都解封了- -
> [...](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "lss233/chatgpt-mirai-qq-bot" ***@***.***&gt;; 发送时间:&nbsp;2023年5月19日(星期五) 下午4:39 ***@***.***&gt;; ***@***.******@***.***&gt;; 主题:&nbsp;Re: [lss233/chatgpt-mirai-qq-bot] [BUG] Poe 登录提示 Something went wrong... (Issue #705) 我的poe也被封号了，不能使用poe，跟使用频率啥的无关 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: ***@***.***&gt;

怎么解封的，它自己会解封吗，现在应该不能用poe的cookie吧，好像poe不允许

**Comment by laoqin6** [comment]
自己解封的










------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "lss233/chatgpt-mirai-qq-bot"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年5月19日(星期五) 下午4:44
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [lss233/chatgpt-mirai-qq-bot] [BUG] Poe 登录提示 Something went wrong... (Issue #705)





  
我的都解封了- -
 ...
 ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "lss233/chatgpt-mirai-qq-bot" @.&gt;; 发送时间:&nbsp;2023年5月19日(星期五) 下午4:39 @.&gt;; @.@.&gt;; 主题:&nbsp;Re: [lss233/chatgpt-mirai-qq-bot] [BUG] Poe 登录提示 Something went wrong... (Issue #705) 我的poe也被封号了，不能使用poe，跟使用频率啥的无关 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: @.***&gt;
  
怎么解封的，它自己会解封吗，现在应该不能用poe的cookie吧，好像poe不允许
